In [107]:
import pandas as pd

In [108]:
df=pd.read_csv("Used Car Dataset.csv")

In [109]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1553 entries, 0 to 1552
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          1553 non-null   int64
 1   car_name            1553 non-null   object
 2   registration_year   1553 non-null   object
 3   insurance_validity  1553 non-null   object
 4   fuel_type           1553 non-null   object
 5   seats               1553 non-null   int64
 6   kms_driven          1553 non-null   int64
 7   ownsership          1553 non-null   object
 8   transmission        1553 non-null   object
 9   manufacturing_year  1553 non-null   object
 10  mileage(kmpl)       1550 non-null   float64
 11  engine(cc)          1550 non-null   float64
 12  max_power(bhp)      1550 non-null   float64
 13  torque(Nm)          1549 non-null   float64
 14  price(in lakhs)     1553 non-null   float64
dtypes: float64(5), int64(3), object(7)
memory usage: 182.1+ KB

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,Comprehensive,Petrol,5,56000,First Owner,Automatic,2017,7.81,2996.0,2996.0,333.0,63.75
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,Comprehensive,Petrol,5,30615,First Owner,Automatic,2020,17.40,999.0,999.0,9863.0,8.99
2,2,2018 BMW X1 sDrive 20d xLine,Sep-18,Comprehensive,Diesel,5,24000,First Owner,Automatic,2018,20.68,1995.0,1995.0,188.0,23.75
3,3,2019 Kia Seltos GTX Plus,Dec-19,Comprehensive,Petrol,5,18378,First Owner,Manual,2019,16.50,1353.0,1353.0,13808.0,13.56
4,4,2019 Skoda Superb LK 1.8 TSI AT,Aug-19,Comprehensive,Petrol,5,44900,First Owner,Automatic,2019,14.67,1798.0,1798.0,17746.0,24.00

In [110]:
df.drop("Unnamed: 0",axis=1,inplace=True)
df.drop("torque(Nm)",axis=1,inplace=True)
df.drop("max_power(bhp)",axis=1,inplace=True)
df.drop("registration_year",axis=1,inplace=True)

In [111]:
# x=df.drop("price(in lakhs)",axis=1)
# y=df["price(in lakhs)"]

In [112]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [113]:
enc=LabelEncoder()
hot=OneHotEncoder()
df

,car_name,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),price(in lakhs)
0,2017 Mercedes-Benz S-Class S400,Comprehensive,Petrol,5,56000,First Owner,Automatic,2017,7.81,2996.0,63.75
1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Comprehensive,Petrol,5,30615,First Owner,Automatic,2020,17.40,999.0,8.99
2,2018 BMW X1 sDrive 20d xLine,Comprehensive,Diesel,5,24000,First Owner,Automatic,2018,20.68,1995.0,23.75
3,2019 Kia Seltos GTX Plus,Comprehensive,Petrol,5,18378,First Owner,Manual,2019,16.50,1353.0,13.56
4,2019 Skoda Superb LK 1.8 TSI AT,Comprehensive,Petrol,5,44900,First Owner,Automatic,2019,14.67,1798.0,24.00
...,...,...,...,...,...,...,...,...,...,...,...
1548,2020 Hyundai Creta SX Opt Diesel AT BSVI,Comprehensive,Diesel,5,35000,First Owner,Automatic,2020,1493.00,11345.0,17.41
1549,2022 Renault KWID 1.0 RXL Opt BSVI,Third Party insurance,Petrol,5,10000,999 cc,2022,Power Steering,999.00,6706.0,3.98
1550,2017 Honda WR-V i-VTEC S,Comprehensive,Petrol,5,49000,First Owner,Manual,2017,17.50,1199.0,5.85
1551,2018 Volkswagen Polo 1.0 MPI Comfortline,Comprehensive,Petrol,5,40000,Second Owner,Manual,2018,18.78,999.0,4.75
1552,2018 Maruti Swift Dzire VXI,Comprehensive,Petrol,5,34756,First Owner,Manual,2018,20.85,1197.0,6.10

In [114]:
fuel=enc.fit_transform(df['fuel_type'])
df.loc[:,["fuel_type"]]=fuel

In [115]:
own=enc.fit_transform(df.loc[:,["ownsership"]])
df.loc[:,["ownsership"]]=own

c:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [116]:
trans=enc.fit_transform(df.loc[:,["transmission"]])
df.loc[:,["transmission"]]=trans

c:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [117]:
car=hot.fit_transform(df.loc[:,["car_name"]]).toarray()
df.loc[:,["car_name"]]=car

ValueError: Must have equal len keys and value when setting with an ndarray

In [ ]:
df.head()

,car_name,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),price(in lakhs)
0,2017 Mercedes-Benz S-Class S400,Comprehensive,3,5,56000,First Owner,Automatic,2017,7.81,2996.0,63.75
1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Comprehensive,3,5,30615,First Owner,Automatic,2020,17.40,999.0,8.99
2,2018 BMW X1 sDrive 20d xLine,Comprehensive,2,5,24000,First Owner,Automatic,2018,20.68,1995.0,23.75
3,2019 Kia Seltos GTX Plus,Comprehensive,3,5,18378,First Owner,Manual,2019,16.50,1353.0,13.56
4,2019 Skoda Superb LK 1.8 TSI AT,Comprehensive,3,5,44900,First Owner,Automatic,2019,14.67,1798.0,24.00

array([3, 3, 2, ..., 3, 3, 3])