In [35]:
import pandas as pd
import numpy as np
import random

In [36]:
df=pd.read_csv("aug_train.csv")

In [37]:
df.head(50)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
5,21651,city_176,0.764,NaN,Has relevent experience,Part time course,Graduate,STEM,11,NaN,NaN,1,24,1.0
6,28806,city_160,0.920,Male,Has relevent experience,no_enrollment,High School,NaN,5,50-99,Funded Startup,1,24,0.0
7,402,city_46,0.762,Male,Has relevent experience,no_enrollment,Graduate,STEM,13,<10,Pvt Ltd,>4,18,1.0
8,27107,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,7,50-99,Pvt Ltd,1,46,1.0
9,699,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,17,10000+,Pvt Ltd,>4,123,0.0
10,29452,city_21,0.624,NaN,No relevent experience,Full time course,High School,NaN,2,NaN,NaN,never,32,1.0
11,23853,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,5,5000-9999,Pvt Ltd,1,108,0.0
12,25619,city_61,0.913,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,1000-4999,Pvt Ltd,3,23,0.0
13,5826,city_21,0.624,Male,No relevent experience,NaN,NaN,NaN,2,NaN,NaN,never,24,0.0
14,8722,city_21,0.624,NaN,No relevent experience,Full time course,High School,NaN,5,NaN,NaN,never,26,0.0
15,6588,city_114,0.926,Male,Has relevent experience,no_enrollment,Graduate,STEM,16,10/49,Pvt Ltd,>4,18,0.0
16,4167,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,1,50-99,Pvt Ltd,never,106,0.0
17,5764,city_21,0.624,NaN,Has relevent experience,no_enrollment,Graduate,STEM,2,5000-9999,Pvt Ltd,2,7,0.0
18,2156,city_21,0.624,NaN,Has relevent experience,no_enrollment,Graduate,STEM,7,10000+,Pvt Ltd,never,23,1.0
19,11399,city_13,0.827,Female,Has relevent experience,no_enrollment,Graduate,Arts,4,NaN,NaN,1,132,1.0
20,31972,city_159,0.843,Male,Has relevent experience,no_enrollment,Masters,STEM,11,100-500,Pvt Ltd,1,68,0.0
21,19061,city_114,0.926,Male,Has relevent experience,no_enrollment,Masters,STEM,11,100-500,Pvt Ltd,2,50,0.0
22,6491,city_102,0.804,NaN,Has relevent experience,no_enrollment,Masters,STEM,10,NaN,NaN,1,48,0.0
23,7041,city_40,0.776,Male,Has relevent experience,no_enrollment,Graduate,Humanities,<1,1000-4999,Pvt Ltd,1,65,0.0
24,22767,city_21,0.624,NaN,Has relevent experience,no_enrollment,Graduate,STEM,5,1000-4999,Pvt Ltd,1,13,0.0
25,14505,city_67,0.855,NaN,No relevent experience,no_enrollment,High School,NaN,4,NaN,NaN,never,22,0.0
26,17139,city_21,0.624,NaN,Has relevent experience,Part time course,Graduate,STEM,14,500-999,Pvt Ltd,1,148,1.0
27,28476,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,Arts,5,NaN,NaN,2,72,0.0
28,21538,city_100,0.887,Male,Has relevent experience,no_enrollment,High School,NaN,11,<10,Pvt Ltd,1,8,1.0
29,10408,city_21,0.624,Male,Has relevent experience,no_enrollment,Graduate,STEM,18,50-99,Funded Startup,2,68,1.0
30,14928,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,100-500,Pvt Ltd,3,40,0.0
31,22293,city_103,0.920,Male,Has relevent experience,Part time course,Graduate,STEM,19,5000-9999,Pvt Ltd,>4,141,0.0
32,4324,city_103,0.920,Female,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,1,24,0.0
33,26966,city_160,0.920,Female,Has relevent experience,no_enrollment,Graduate,STEM,>20,100-500,Pvt Ltd,>4,82,0.0
34,26494,city_16,0.910,Male,Has relevent experience,no_enrollment,Graduate,Business Degree,12,5000-9999,Pvt Ltd,3,145,0.0
35,4866,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,10,10/49,Early Stage Startup,2,206,0.0
36,12726,city_114,0.926,Male,No relevent experience,Part time course,High School,NaN,1,10000+,Other,1,152,0.0
37,10164,city_114,0.926,Male,Has relevent experience,no_enrollment,Phd,STEM,>20,100-500,Pvt Ltd,4,42,1.0
38,8612,city_103,0.920,NaN,No relevent experience,no_enrollment,Graduate,STEM,12,NaN,NaN,4,50,0.0
39,24659,city_71,0.884,Male,No relevent experience,no_enrollment,NaN,NaN,3,NaN,NaN,never,106,0.0
40,2547,city_114,0.926,Female,Has relevent experience,Full time course,Masters,STEM,16,1000-4999,Public Sector,2,14,0.0
41,13854,city_104,0.924,Male,Has relevent experience,no_enrollment,High School,NaN,4,10/49,Pvt Ltd,2,36,0.0
42,31654,city_21,0.624,NaN,Has relevent experience,no_enrollment,Masters,STEM,6,50-99,Early Stage Startup,1,112,1.0
43,13643,city_64,0.666,NaN,No relevent experience,no_enrollment,Graduate,No Major,9,50-99,Pvt Ltd,never,108,0.0
44,5590,city_21,0.624,Male,Has relevent experience,Part time course,Masters,STEM,9,5000-9999,Pvt Ltd,3,7,1.0
45,22452,city_21,0.624,Female,No relevent experience,Full time course,Masters,STEM,5,NaN,NaN,never,26,1.0
46,9006,city_21,0.624,Male,Has relevent experience,no_enrollment,Graduate,STEM,5,100-500,Pvt Ltd,never,87,1.0
47,25987,city_103,0.920,Other,Has relevent experience,no_enrollment,Graduate,STEM,19,10000+,Public Sector,4,52,1.0
48,4476,city_101,0.558,Male,Has relevent experience,no_enrollment,Graduate,No Major,15,NaN,NaN,>4,20,1.0
49,25103,city_83,0.923,Male,Has relevent experience,no_enrollment,Graduate,STEM,11,10/49,Pvt Ltd,1,21,0.0

In [38]:
df.tail(30)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
19128,3365,city_16,0.910,NaN,Has relevent experience,no_enrollment,Graduate,Humanities,>20,1000-4999,Pvt Ltd,>4,23,0.0
19129,9651,city_100,0.887,NaN,No relevent experience,Full time course,Masters,STEM,3,NaN,Public Sector,1,30,1.0
19130,20668,city_21,0.624,Male,Has relevent experience,no_enrollment,Graduate,STEM,11,100-500,Pvt Ltd,>4,25,0.0
19131,18072,city_116,0.743,Male,No relevent experience,no_enrollment,Masters,STEM,8,10000+,NaN,1,48,0.0
19132,15549,city_36,0.893,Male,Has relevent experience,no_enrollment,Graduate,STEM,10,500-999,Pvt Ltd,1,67,0.0
19133,25191,city_10,0.895,Other,Has relevent experience,no_enrollment,Graduate,STEM,16,10/49,Pvt Ltd,1,36,0.0
19134,28798,city_103,0.920,Male,Has relevent experience,Part time course,High School,NaN,12,500-999,Pvt Ltd,>4,13,0.0
19135,20520,city_65,0.802,Male,Has relevent experience,no_enrollment,Graduate,STEM,8,50-99,Public Sector,2,136,0.0
19136,23672,city_21,0.624,NaN,Has relevent experience,no_enrollment,Masters,STEM,6,NaN,NaN,1,5,1.0
19137,22620,city_21,0.624,NaN,Has relevent experience,no_enrollment,Graduate,STEM,8,50-99,Pvt Ltd,>4,80,0.0
19138,19765,city_30,0.698,NaN,Has relevent experience,no_enrollment,Masters,STEM,11,100-500,Pvt Ltd,1,17,0.0
19139,5603,city_21,0.624,NaN,Has relevent experience,Full time course,Graduate,STEM,4,NaN,NaN,NaN,13,0.0
19140,11398,city_103,0.920,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,never,15,0.0
19141,7782,city_23,0.899,Male,Has relevent experience,no_enrollment,Graduate,STEM,17,10/49,Funded Startup,3,12,0.0
19142,13750,city_40,0.776,Male,Has relevent experience,no_enrollment,NaN,NaN,5,10/49,Early Stage Startup,1,26,0.0
19143,33047,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,10000+,Pvt Ltd,>4,18,0.0
19144,17191,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,4,NaN,NaN,never,48,1.0
19145,155,city_44,0.725,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,Pvt Ltd,never,190,0.0
19146,13167,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,5,500-999,Pvt Ltd,1,51,0.0
19147,21319,city_21,0.624,Male,No relevent experience,Full time course,Graduate,STEM,1,100-500,Pvt Ltd,1,52,1.0
19148,9212,city_21,0.624,NaN,Has relevent experience,no_enrollment,Masters,STEM,3,100-500,Pvt Ltd,3,40,1.0
19149,251,city_103,0.920,Male,Has relevent experience,no_enrollment,Masters,STEM,9,50-99,Pvt Ltd,1,36,1.0
19150,32313,city_160,0.920,Female,Has relevent experience,no_enrollment,Graduate,STEM,10,100-500,Public Sector,3,23,0.0
19151,11385,city_149,0.689,Male,No relevent experience,Full time course,Graduate,NaN,2,NaN,NaN,1,60,0.0
19152,29754,city_103,0.920,Female,Has relevent experience,no_enrollment,Graduate,Humanities,7,10/49,Funded Startup,1,25,0.0
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [39]:
df.isnull().sum()

enrollee_id                  0
city                         0
city_development_index       0
gender                    4508
relevent_experience          0
enrolled_university        386
education_level            460
major_discipline          2813
experience                  65
company_size              5938
company_type              6140
last_new_job               423
training_hours               0
target                       0
dtype: int64

In [40]:
df.loc[1,:]

enrollee_id                                29725
city                                     city_40
city_development_index                     0.776
gender                                      Male
relevent_experience       No relevent experience
enrolled_university                no_enrollment
education_level                         Graduate
major_discipline                            STEM
experience                                    15
company_size                               50-99
company_type                             Pvt Ltd
last_new_job                                  >4
training_hours                                47
target                                       0.0
Name: 1, dtype: object

In [ ]:
a=(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20)
b=random.choice(a)

5